# IMPORTING LIBRARY

In [1]:
import numpy as np
import pandas as pd 
import random

# IMPORTING DATA

In [2]:
df=pd.read_csv(r"C:\Users\rohit\OneDrive\Desktop\RAJAT'S WORK\FRAUD DETECTION\normal user.csv")
df1=pd.read_csv(r"C:\Users\rohit\OneDrive\Desktop\RAJAT'S WORK\FRAUD DETECTION\block user.csv")
df

,USERIDs,JoiningFeeCount,AppLaunchCount,DaysSpent,PayTmLink,FreeGamePlayedCount,FreeGamePlayedAmount,PaidGamePlayedCount,PaidGamePlayedAmount,FantasyGameCount,...,RummyGameCount,RummyGameAmount,CallBreakGameCount,CallBreakGameAmount,DepositCount,DepositAmount,RedeemCount,RedeemAmount,PaidGamePlayedWinRatio,PaidGamePlayedLossRatio
0,127679246,1,2,0,1,0,0,0,0,0,...,0,0,4,40,0,0,0,0,0.00,0.00
1,127679247,0,1086,199,1,0,0,5156,48794,22,...,5,5,15,80,5156,48794,5156,48794,28.37,71.63
2,127679248,0,40,132,0,0,0,4,4,1,...,2,2,58,441,4,4,4,4,25.00,75.00
3,127679249,1,1715,131,1,0,0,4727,12651,178,...,7841,20362,0,0,4727,12651,4727,12651,20.44,79.56
4,127679250,1,3,4,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0.00,0.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
206047,127889791,0,2,0,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0.00,0.00
206048,127889792,0,5,29,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0.00,0.00
206049,127889793,0,18,40,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0.00,0.00
206050,127889794,1,2,0,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0.00,0.00
206051,127889795,0,260,167,0,0,0,61,182,0,...,2,3,115,334,61,182,61,182,42.62,57.38

In [3]:
df1

,USERIDs,JoiningFeeCount,JoiningFeeAmount,AppLaunchCount,DaysSpent,PayTmLink,FreeGameAllowed,FreeGamePlayed,PaidGamePlayedCount,PaidGamePlayedAmount,...,CallBreakGameCount,CallBreakGameAmount,DepositCount,DepositAmount,RedeemCount,RedeemAmount,PaidGamePlayedWinRatio,PaidGamePlayedLossRatio,CasualGameCount,CasualGameAmount
0,126147307,0,0,10,0,0,0,0.0,0,0.000000,...,0,0.0,0,0.0,0,0.0,0.00,0.00,0,0.0
1,126147330,0,0,26,9,0,0,0.0,0,0.000000,...,0,0.0,0,0.0,0,0.0,0.00,0.00,0,0.0
2,126147376,1,20,13,1,1,0,0.0,0,0.000000,...,4,14.0,0,0.0,0,0.0,0.00,0.00,5,8.0
3,126147381,0,0,135,34,1,0,0.0,0,0.000000,...,277,963.0,18,360.0,0,0.0,0.00,0.00,61,73.0
4,126147409,0,0,393,190,1,0,0.0,0,0.000000,...,43,160.0,20,16918.0,10,20010.0,0.00,0.00,70,79.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
55613,129940610,0,0,7,0,0,5,0.0,49,181.720001,...,0,0.0,0,0.0,0,0.0,40.82,59.18,5,7.0
55614,129940728,0,0,0,0,0,0,0.0,0,0.000000,...,0,0.0,0,0.0,0,0.0,0.00,0.00,0,0.0
55615,129941036,0,0,3,0,1,0,0.0,0,0.000000,...,0,0.0,0,0.0,0,0.0,0.00,0.00,0,0.0
55616,129941486,0,0,0,0,0,0,0.0,0,0.000000,...,0,0.0,0,0.0,0,0.0,0.00,0.00,0,0.0
55617,129941495,0,0,0,0,0,0,0.0,0,0.000000,...,0,0.0,0,0.0,0,0.0,0.00,0.00,0,0.0

# DATA PREPROCESSING

In [4]:
def preprocessing(df):
    df = df[df.AppLaunchCount>0]
    df = df[df.DaysSpent>0]
    df = df[df.DepositCount>0]
    df = df[df.DepositAmount>0]
    df = df[df.RedeemCount>0]
    return df

# COMOPARING FUNCTION

In [5]:
def meanofdata(df,df1,start,end,interval):
    
    days=[]
    for i in range(start,end+interval,interval):
        days.append(i)
    
    DAYS=[]
    for i in range(len(days)-1):
        DAYS.append("{} - {}".format(days[i],days[i+1]))

#   UNBLOCK USER
    list1,list2,list3,list4,list5=[],[],[],[],[]
    for i in range(len(days)-1):
        temp=df[(df.DaysSpent>=days[i]+1) & (df.DaysSpent<=days[i+1])]
        val1=temp.DepositCount.mean()
        list1.append(val1)
        val2=temp.DepositAmount.mean()
        list2.append(val2)
        val3=temp.RedeemCount.mean()
        list3.append(val3)
        val4=temp.RedeemAmount.mean()
        list4.append(val4)
        val5=temp.PaidGamePlayedWinRatio.mean()
        list5.append(val5)
        temp=df
    dataframe1=pd.DataFrame(list(zip(DAYS,list1,list2,list3,list4,list5)),columns=["Days","meanofDepositCount","meanofDepositAmount","meanofRedeemCount","meanofRedeemAmount","meanofwinratio"])

#   BLOCK USER
    list1,list2,list3,list4,list5=[],[],[],[],[]
    for i in range(len(days)-1):
        temp=df1[(df1.DaysSpent>=days[i]+1) & (df1.DaysSpent<=days[i+1])]
        val1=temp.DepositCount.mean()
        list1.append(val1)
        val2=temp.DepositAmount.mean()
        list2.append(val2)
        val3=temp.RedeemCount.mean()
        list3.append(val3)
        val4=temp.RedeemAmount.mean()
        list4.append(val4)
        val5=temp.PaidGamePlayedWinRatio.mean()
        list5.append(val5)
        temp=df
    dataframe2=pd.DataFrame(list(zip(DAYS,list1,list2,list3,list4,list5)),columns=["Days","DepositCount","DepositAmount","RedeemCount","RedeemAmount","winratio"])

#   COMPARISION BETWEEN BLOCK AND UNBLOCKED DATA
    list1=dataframe2.DepositCount/dataframe1.meanofDepositCount
    list2=dataframe2.DepositAmount/dataframe1.meanofDepositAmount
    list3=dataframe2.RedeemCount/dataframe1.meanofRedeemCount
    list4=dataframe2.RedeemAmount/dataframe1.meanofRedeemAmount
    list5=dataframe2.winratio/dataframe1.meanofwinratio
    finaldf=pd.DataFrame(list(zip(DAYS,list1,list2,list3,list4,list5)),columns=["days","DepositCount","DepositAmount","RedeemCount","RedeemAmount","winratio"])
    return finaldf
temp=preprocessing(df)
temp1=preprocessing(df1)
start=0
end=50
interval=5
finaldf=meanofdata(temp,temp1,start,end,interval)

# FINAL DATA FRAME

In [6]:
finaldf

      days  DepositCount  DepositAmount  RedeemCount  RedeemAmount  winratio
0    0 - 5      2.827000     681.459000     1.538000   1459.990000  0.142329
1   5 - 10      5.505518    1318.529871     2.412957   2445.834285  0.102338
2  10 - 15      7.841897    1543.772907     2.615882   2306.652294  0.154267
3  15 - 20      8.483455    2661.277547     3.313496   3761.509009  0.123126
4  20 - 25      9.309053    2016.553590     2.865765   3153.215401  0.081957
5  25 - 30     12.923274    3017.158568     4.529412   4625.447570  0.114535
6  30 - 35     11.431587    3390.869923     3.762425   5039.304209  0.150419
7  35 - 40     15.132180    3663.606920     4.546251   5057.644752  0.105268
8  40 - 45      2.348710      61.182927     0.655013     79.845297  0.289969
9  45 - 50      1.093823      21.039294     0.304950     27.490389  0.507556

# ANOMALY DETECTION

In [10]:
def frauddetection(userid,k,DataFrame):
    count=0
    #blocked user 
#     user=df1[df1['USERIDs']==userid]
    #unblocked user
    user=df[df['USERIDs']==userid]
    
    days=user.DaysSpent.iloc[0]
    
    #FIRST
    if days >=0 or days<5:
        if user.DepositCount.iloc[0] > DataFrame.DepositCount.iloc[0]/k:
            count+=1
        if user.DepositAmount.iloc[0] > DataFrame.DepositAmount.iloc[0]/k:
            count+=1
        if user.RedeemCount.iloc[0] > DataFrame.RedeemCount[0]/k:
            count+=1
        if user.RedeemAmount.iloc[0] > DataFrame.RedeemAmount[0]/k:
            count+=1
        if user.PaidGamePlayedWinRatio.iloc[0]>DataFrame.winratio[0]/k:
            count+=1
    
    # SECOND
    elif days >=5 or days<10:
        if user.DepositCount.iloc[0] > DataFrame.DepositCount.iloc[1]/k:
            count+=1
        if user.DepositAmount.iloc[0] > DataFrame.DepositAmount.iloc[1]/k:
            count+=1
        if user.RedeemCount.iloc[0] > DataFrame.RedeemCount[1]/k:
            count+=1
        if user.RedeemAmount.iloc[0] > DataFrame.RedeemAmount[1]/k:
            count+=1
        if user.PaidGamePlayedWinRatio.iloc[0]>DataFrame.winratio[1]/k:
            count+=1
    
    # THIRD
    elif days >= 10 or days<15:
        if user.DepositCount.iloc[0] > DataFrame.DepositCount.iloc[2]/k:
            count+=1
        if user.DepositAmount.iloc[0] > DataFrame.DepositAmount.iloc[2]/k:
            count+=1
        if user.RedeemCount.iloc[0] > DataFrame.RedeemCount[2]/k:
            count+=1
        if user.RedeemAmount.iloc[0] > DataFrame.RedeemAmount[2]/k:
            count+=1
        if user.PaidGamePlayedWinRatio.iloc[0]>DataFrame.winratio[2]/k:
            count+=1
    
    # FOURTH
    elif days>=15 or days<20:
        if user.DepositCount.iloc[0] > DataFrame.DepositCount.iloc[3]/k:
            count+=1
        if user.DepositAmount.iloc[0] > DataFrame.DepositAmount.iloc[3]/k:
            count+=1
        if user.RedeemCount.iloc[0] > DataFrame.RedeemCount[3]/k:
            count+=1
        if user.RedeemAmount.iloc[0] > DataFrame.RedeemAmount[3]/k:
            count+=1
        if user.PaidGamePlayedWinRatio.iloc[0]>DataFrame.winratio[3]/k:
            count+=1

    #FIVE			
    elif days>=20 or days<25:
        if user.DepositCount.iloc[0] > DataFrame.DepositCount.iloc[4]/k:
            count+=1
        if user.DepositAmount.iloc[0] > DataFrame.DepositAmount.iloc[4]/k:
            count+=1
        if user.RedeemCount.iloc[0] > DataFrame.RedeemCount[4]/k:
            count+=1
        if user.RedeemAmount.iloc[0] > DataFrame.RedeemAmount[4]/k:
            count+=1
        if user.PaidGamePlayedWinRatio.iloc[0]>DataFrame.winratio[4]/k:
            count+=1
            
    #SIXTH			
    elif days>=25 or days<30:
        if user.DepositCount.iloc[0] > DataFrame.DepositCount.iloc[5]/k:
            count+=1
        if user.DepositAmount.iloc[0] > DataFrame.DepositAmount.iloc[5]/k:
            count+=1
        if user.RedeemCount.iloc[0] > DataFrame.RedeemCount[5]/k:
            count+=1
        if user.RedeemAmount.iloc[0] > DataFrame.RedeemAmount[5]/k:
            count+=1
        if user.PaidGamePlayedWinRatio.iloc[0]>DataFrame.winratio[5]/k:
            count+=1

    #SEVENTH 			
    elif days>=30 or days<35:
        if user.DepositCount.iloc[0] > DataFrame.DepositCount.iloc[6]/k:
            count+=1
        if user.DepositAmount.iloc[0] > DataFrame.DepositAmount.iloc[6]/k:
            count+=1
        if user.RedeemCount.iloc[0] > DataFrame.RedeemCount[6]/k:
            count+=1
        if user.RedeemAmount.iloc[0] > DataFrame.RedeemAmount[6]/k:
            count+=1
        if user.PaidGamePlayedWinRatio.iloc[0]>DataFrame.winratio[6]/k:
            count+=1

    #EIGHT 			
    elif days>=35 or days<40:
        if user.DepositCount.iloc[0] > DataFrame.DepositCount.iloc[7]/k:
            count+=1
        if user.DepositAmount.iloc[0] > DataFrame.DepositAmount.iloc[7]/k:
            count+=1
        if user.RedeemCount.iloc[0] > DataFrame.RedeemCount[7]/k:
            count+=1
        if user.RedeemAmount.iloc[0] > DataFrame.RedeemAmount[7]/k:
            count+=1
        if user.PaidGamePlayedWinRatio.iloc[0]>DataFrame.winratio[7]/k:
            count+=1
            
    if count>=4:
        return "the user is a fraud user"
    else:
        return "the user is not fraud"

# PERFORMANCE OF MODEL

In [8]:
#ON BLOCKED USER
l1=[]
k=2
temp=preprocessing(df1)

for i in range(10):
    l1.append(random.randrange(10, 1000,10))

useridlist=[]
for i in l1:
    useridlist.append(temp.USERIDs.iloc[i])

temp=preprocessing(df)
temp1=preprocessing(df1)
start=0
end=50
interval=5
DataFrame=meanofdata(temp,temp1,start,end,interval)
    
for userid in useridlist:
    print(frauddetection(userid,k,DataFrame))

the user is a fraud user
the user is a fraud user
the user is a fraud user
the user is not fraud
the user is not fraud
the user is a fraud user
the user is a fraud user
the user is not fraud
the user is a fraud user
the user is not fraud

In [12]:
#ON UNBLOCKED USER
l1=[]
k=2
temp=preprocessing(df)

for i in range(10):
    l1.append(random.randrange(10, 1000,10))

useridlist=[]
for i in l1:
    useridlist.append(temp.USERIDs.iloc[i])

temp=preprocessing(df)
temp1=preprocessing(df1)
start=0
end=50
interval=5
DataFrame=meanofdata(temp,temp1,start,end,interval)
    
for userid in useridlist:
    print(frauddetection(userid,k,DataFrame))

the user is a fraud user
the user is not fraud
the user is a fraud user
the user is a fraud user
the user is not fraud
the user is a fraud user
the user is a fraud user
the user is a fraud user
the user is a fraud user
the user is not fraud